#!/bin/sh

exec cat<<EOF
   Operator                                             Assoc
================================================================
#                                                              #
#  ()   []   ->   .                                     L to R #
#  !    ~    ++   --   -   (type)  *   &    sizeof      R to L #
#  *    /    %                                          L to R #
#  +    -                                               L to R #
#  <<   >>                                              L to R #
#  <    <=   >    >=                                    L to R #
#  ==   !=                                              L to R #
#  &                                                    L to R #
#  ^                                                    L to R #
#  |                                                    L to R #
#  &&                                                   L to R #
#  ||                                                   L to R #
#  ?:                                                   R to L #
#  =    +=   -=   etc.                                  R to L #
#  ,                                                    L to R #
#                                                              #
#==============================================================#
EOF
